## 捕获全局异常

### 描述

构建一个流程，在流程中节点处理异常时能够捕获异常信息，并进行日志输出。

### 使用特性

`close`

### 示例代码

#### pom

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>modelengine.fit.demo</groupId>
    <artifactId>waterflow-demo</artifactId>
    <version>1.0.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>8</maven.compiler.source>
        <maven.compiler.target>8</maven.compiler.target>
    </properties>

    <dependencies>
        <dependency>
            <groupId>modelengine.fit.jade.waterflow</groupId>
            <artifactId>waterflow-core</artifactId>
            <version>1.0.0-SNAPSHOT</version>
        </dependency>
    </dependencies>
</project>
```

#### 代码

``` java
import modelengine.fit.waterflow.domain.flow.Flows;
import modelengine.fit.waterflow.domain.flow.ProcessFlow;

import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;

public class Main {
    public static void main(String[] args) throws InterruptedException {
        List<Integer> result = new ArrayList<>();
        ProcessFlow flow = Flows.<String>create()
                .map(v -> Integer.parseInt(v))
                .close(res -> result.addAll(res.getAll().stream().map(c -> c.getData()).collect(Collectors.toList())),
                        (exception, retryable, flowContexts) -> {
                            System.out.println(
                                    String.format("exception=%s:%s, flowContextSize=%d", exception.getClass().getName(),
                                            exception.getMessage(), flowContexts.size()));
                        });
        flow.offer("1");
        flow.offer("two");
        flow.offer("3");
        Thread.sleep(1000);
        System.out.println("result: " + result);
        result.clear();
        flow.offer(new String[] {"1", "two", "3"});
        Thread.sleep(1000);
        System.out.println("result: " + result);
    }
}
```

> 1. 这里在`close`时分别指定结果回调和异常捕获回调。
> 2. 其中`exception`为具体的异常信息，`flowContexts`为本批失败对应的所有数据。
> 3. 如果一批数据中有一个数据异常，则是该批数据全部失败。

#### 运行结果

```
exception=java.lang.NumberFormatException:For input string: "two", flowContextSize=1
result: [1, 3]
exception=java.lang.NumberFormatException:For input string: "two", flowContextSize=3
result: []
```

> 1. 前面`1, two, 3`是分别独立offer的，`1,3`是能够独立正常运行结束并追加到`result`中。
> 2. `flow.offer(new String[] {"1", "two", "3"})`为一批数据，其中`two`处理异常失败后，该批的所有数据均不会正常运行结束，则`result`中不会有数据。此时，异常回调中的`flowContexts`包含了这三个数据。

## 捕获节点异常

### 描述

构建一个流程，在流程中节点处理异常时捕获该节点异常信息，并进行日志输出。

### 使用特性

`error`

### 示例代码

#### pom

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>modelengine.fit.demo</groupId>
    <artifactId>waterflow-demo</artifactId>
    <version>1.0.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>8</maven.compiler.source>
        <maven.compiler.target>8</maven.compiler.target>
    </properties>

    <dependencies>
        <dependency>
            <groupId>modelengine.fit.jade.waterflow</groupId>
            <artifactId>waterflow-core</artifactId>
            <version>1.0.0-SNAPSHOT</version>
        </dependency>
    </dependencies>
</project>
```

#### 代码

``` java
import modelengine.fit.waterflow.domain.flow.Flows;
import modelengine.fit.waterflow.domain.flow.ProcessFlow;

import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;

public class Main {
    public static void main(String[] args) throws InterruptedException {
        List<Integer> result = new ArrayList<>();
        ProcessFlow flow = Flows.<String>create()
                .map(v -> Integer.parseInt(v))
                .error((exception, retryable, flowContexts) -> {
                    System.out.println(
                    String.format("exception=%s:%s, flowContextSize=%d", exception.getClass().getName(),
                            exception.getMessage(), flowContexts.size()));
                    })

                .close(res -> result.addAll(res.getAll().stream().map(c -> c.getData()).collect(Collectors.toList())));
        flow.offer("1");
        flow.offer("two");
        flow.offer("3");
        Thread.sleep(1000);
        System.out.println("result: " + result);
        result.clear();
        flow.offer(new String[] {"1", "two", "3"});
        Thread.sleep(1000);
        System.out.println("result: " + result);
    }
}
```

> 1. 这里在`map`后跟随`error`捕获该节点执行异常的回调。
> 2. `error`指定的内容只捕获前面节点`map`中的异常。
> 3. 其中`exception`为具体的异常信息，`flowContexts`为本批失败对应的所有数据。
> 4. 如果一批数据中有一个数据异常，则是该批数据全部失败。

#### 运行结果

```
exception=java.lang.NumberFormatException:For input string: "two", flowContextSize=1
result: [1, 3]
exception=java.lang.NumberFormatException:For input string: "two", flowContextSize=3
result: []
```

> 1. 前面`1, two, 3`是分别独立offer的，`1,3`是能够独立正常运行结束并追加到`result`中。
> 2. `flow.offer(new String[] {"1", "two", "3"})`为一批数据，其中`two`处理异常失败后，该批的所有数据均不会正常运行结束，则`result`中不会有数据。此时，异常回调中的`flowContexts`包含了这三个数据。
> 3. `error`只捕获前一个节点的异常，如果在`error`前增加一行`.just(v -> {})`，则`map`中的异常不再输出。
